export const constantActions = {
	ACTION_START: 'ACTION_START',
	ACTION_SUCCESS: 'ACTION_SUCCESS',
	ACTION_FAIL: 'ACTION_FAIL',
	ACTION_SEARCH:'ACTION_SEARCH'
};
export const ACTION_START = 'ACTION_START'
